### ISSUE TITLE
Cannot open source file

### ISSUE THREAD

**Issue by FlagHacks** [alextusinean/tusiphobia#8] opened 2023-01-13 20:20 UTC
when i try to build it, it gives me two errors

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: '..\imgui\backends\imgui_impl_win32.cpp': No such file or directory	tusiphobia	C:\Users\flagf\Downloads\tusiphobia-master\tusiphobia-master\tusiphobia\c1xx	1	
```

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: '..\imgui\backends\imgui_impl_dx11.cpp': No such file or directory	tusiphobia	C:\Users\flagf\Downloads\tusiphobia-master\tusiphobia-master\tusiphobia\c1xx	1	
`

**Comment by alextusinean** [comment] 2023-01-14 11:27
Duplicate of #5.

**Closed by alextusinean** 2023-01-14 11:27 UTC
Labels: duplicate
